"use client";
import type {StudioDraft} from "@/lib/cv-studio";
const fonts=["Arial","Calibri","Cambria","Garamond","Georgia","Helvetica","Times New Roman"];
export function DesignPanel({draft,onChange}:{draft:StudioDraft;onChange:(d:StudioDraft)=>void}){const u=(k:keyof StudioDraft,v:any)=>onChange({...draft,[k]:v});const photo=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>u("photoUrl",String(r.result||""));r.readAsDataURL(f)};return <section className="studio-design-panel"><header className="studio-editor-header"><span>Design studio</span><h2>Customize your CV</h2><p>Control layout, typography, spacing, colours and professional photo.</p></header>
<div className="design-group"><h3>Layout</h3><div className="design-choice-grid">{[["one-column","One column"],["two-column","Two columns"]].map(([v,l])=><button type="button" key={v} className={draft.layout===v?"active":""} onClick={()=>u("layout",v)}><span className={`layout-preview ${v}`}/><strong>{l}</strong></button>)}</div></div>
<div className="design-group"><h3>Header style</h3><div className="design-choice-grid four">{["classic","centered","banded","minimal"].map(v=><button type="button" key={v} className={draft.headerStyle===v?"active":""} onClick={()=>u("headerStyle",v)}><span className={`header-style-preview ${v}`}/><strong>{v[0].toUpperCase()+v.slice(1)}</strong></button>)}</div></div>
<div className="design-group"><h3>Typography</h3><div className="studio-form-grid"><label className="studio-field"><span>Body font</span><select value={draft.fontFamily} onChange={e=>u("fontFamily",e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select></label><label className="studio-field"><span>Heading font</span><select value={draft.headingFont} onChange={e=>u("headingFont",e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select></label><label className="studio-field"><span>Font size: {draft.fontSize}px</span><input type="range" min="10" max="15" value={draft.fontSize} onChange={e=>u("fontSize",Number(e.target.value))}/></label><label className="studio-field"><span>Line height: {draft.lineHeight.toFixed(1)}</span><input type="range" min="1.2" max="1.9" step="0.1" value={draft.lineHeight} onChange={e=>u("lineHeight",Number(e.target.value))}/></label></div></div>
<div className="design-group"><h3>Spacing</h3><div className="studio-form-grid"><label className="studio-field"><span>Margins</span><select value={draft.margin} onChange={e=>u("margin",e.target.value)}><option value="narrow">Narrow</option><option value="standard">Standard</option><option value="wide">Wide</option></select></label><label className="studio-field"><span>Section spacing: {draft.sectionSpacing}px</span><input type="range" min="12" max="36" value={draft.sectionSpacing} onChange={e=>u("sectionSpacing",Number(e.target.value))}/></label></div></div>
<div className="design-group"><h3>Colours</h3><div className="studio-form-grid"><label className="studio-field"><span>Primary accent</span><input type="color" value={draft.accent} onChange={e=>u("accent",e.target.value)}/></label><label className="studio-field"><span>Secondary accent</span><input type="color" value={draft.secondaryAccent} onChange={e=>u("secondaryAccent",e.target.value)}/></label></div><div className="preset-colours">{["#006943","#1f4e79","#7a3e3e","#5a4a78","#1d6d80","#2f2f2f"].map(c=><button type="button" key={c} style={{background:c}} onClick={()=>u("accent",c)}/>)}</div></div>
<div className="design-group"><h3>Professional photo</h3><label className="design-toggle"><input type="checkbox" checked={draft.showPhoto} onChange={e=>u("showPhoto",e.target.checked)}/> Show photo on CV</label>{draft.showPhoto&&<><label className="photo-upload"><input type="file" accept="image/*" onChange={photo}/><span>{draft.photoUrl?"Replace photo":"Upload professional photo"}</span></label><div className="design-choice-grid three">{["circle","square","rounded"].map(v=><button type="button" key={v} className={draft.photoShape===v?"active":""} onClick={()=>u("photoShape",v)}><span className={`photo-shape-preview ${v}`}/><strong>{v[0].toUpperCase()+v.slice(1)}</strong></button>)}</div></>}</div></section>}
