"use client";
import type {StudioDraft,StudioSection} from "@/lib/cv-studio";
const txt=(r:Record<string,unknown>,k:string)=>String(r[k]??"");
export function EditorPanel({draft,active,onChange}:{draft:StudioDraft;active:StudioSection;onChange:(d:StudioDraft)=>void}){
 const profile=(k:keyof StudioDraft["profile"],v:string)=>onChange({...draft,profile:{...draft.profile,[k]:v}});
 if(active==="profile") return <Panel title="Personal details" description="These details appear in your CV header."><div className="studio-form-grid"><Field label="Full name" value={draft.profile.fullName} onChange={v=>profile("fullName",v)}/><Field label="Professional title" value={draft.profile.professionalTitle} onChange={v=>profile("professionalTitle",v)}/><Field label="Email" value={draft.profile.email} onChange={v=>profile("email",v)}/><Field label="Phone" value={draft.profile.phone} onChange={v=>profile("phone",v)}/><Field label="Location" value={draft.profile.location} onChange={v=>profile("location",v)}/><Field label="LinkedIn" value={draft.profile.linkedin} onChange={v=>profile("linkedin",v)}/><Field label="Website" value={draft.profile.website} onChange={v=>profile("website",v)}/></div></Panel>;
 if(active==="summary") return <Panel title="Professional summary" description="Write a concise and targeted introduction."><label className="studio-field"><span>Summary</span><textarea value={draft.profile.summary} maxLength={700} onChange={e=>profile("summary",e.target.value)}/><small>{draft.profile.summary.length} / 700 characters</small></label></Panel>;
 const configs:any={experience:{title:"Professional experience",fields:[["job_title","Job title"],["company","Company"],["location","Location"],["start_date","Start date"],["end_date","End date"],["description","Description"]],empty:{job_title:"",company:"",location:"",start_date:"",end_date:"",description:""}},education:{title:"Education",fields:[["qualification","Qualification"],["institution","Institution"],["field_of_study","Field of study"],["start_date","Start date"],["end_date","End date"],["description","Description"]],empty:{qualification:"",institution:"",field_of_study:"",start_date:"",end_date:"",description:""}},skills:{title:"Skills",fields:[["name","Skill"],["proficiency","Proficiency"],["years_experience","Years experience"]],empty:{name:"",proficiency:"",years_experience:""}},projects:{title:"Projects",fields:[["name","Project name"],["project_url","Project URL"],["description","Description"]],empty:{name:"",project_url:"",description:""}},certifications:{title:"Certifications",fields:[["name","Certification"],["issuer","Issuer"],["issue_date","Issue date"]],empty:{name:"",issuer:"",issue_date:""}},languages:{title:"Languages",fields:[["name","Language"],["proficiency","Proficiency"]],empty:{name:"",proficiency:""}},references:{title:"References",fields:[["full_name","Full name"],["relationship","Relationship"],["company","Company"],["email","Email"],["phone","Phone"]],empty:{full_name:"",relationship:"",company:"",email:"",phone:""}}};
 const c=configs[active]; const items=(draft as any)[active] as Record<string,unknown>[];
 const update=(i:number,k:string,v:string)=>{const n=[...items];n[i]={...n[i],[k]:v};onChange({...draft,[active]:n})};
 const remove=(i:number)=>onChange({...draft,[active]:items.filter((_,x)=>x!==i)});
 const add=()=>onChange({...draft,[active]:[...items,c.empty]});
 return <Panel title={c.title} description="Edit, add or remove entries. Changes appear instantly."><div className="studio-entry-stack">{items.map((item,i)=><article className="studio-entry-card" key={String(item.id||i)}><div className="studio-entry-number">{i+1}</div><div className="studio-form-grid">{c.fields.map(([k,l]:string[])=><Field key={k} label={l} value={txt(item,k)} textarea={k==="description"} onChange={v=>update(i,k,v)}/>)}</div><button className="studio-remove-button" onClick={()=>remove(i)}>Remove</button></article>)}</div><button className="studio-add-button" onClick={add}>+ Add {c.title.toLowerCase()}</button></Panel>
}
function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="studio-editor-panel"><header className="studio-editor-header"><span>Editing section</span><h2>{title}</h2><p>{description}</p></header>{children}</section>}
function Field({label,value,onChange,textarea=false}:{label:string;value:string;onChange:(v:string)=>void;textarea?:boolean}){return <label className={`studio-field ${textarea?"full":""}`}><span>{label}</span>{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
