"use client";

import Link from "next/link";
import { useState } from "react";
import { CheckCircle2, CreditCard, Download, FileCheck2, LoaderCircle, ShieldCheck, Sparkles } from "lucide-react";
import { DISPLAY_PLANS, formatZar, type PlanId } from "@/lib/billing";

type BackendPlanCode="trial_14_day"|"premium_30_day";
type PaymentResponse={authorization_url?:string;detail?:string|{message?:string}};
const benefits:Record<PlanId,string[]>={trial_14_days:["Unlimited CV creation and editing for 14 days","AI CV Builder, CV Revamp and CV Studio","ATS analysis and recruiter-ready templates","PDF and DOCX document exports"],premium_30_days:["Unlimited CV creation and editing for 30 days","Complete AI Career Engine and Career Copilot","Cover letters and interview preparation","Job matching, skills-gap and market insights","Priority access to premium career tools"]};
const shared=[{title:"Career documents",text:"Create, improve and export professional CVs and cover letters.",icon:FileCheck2},{title:"AI career tools",text:"Use evidence-based writing guidance, ATS analysis and career intelligence.",icon:Sparkles},{title:"Secure downloads",text:"Save supported documents in PDF and DOCX formats.",icon:Download}];

function backendCode(plan:PlanId):BackendPlanCode{return plan==="trial_14_days"?"trial_14_day":"premium_30_day"}
function errorMessage(response:PaymentResponse|null,status:number){if(typeof response?.detail==="string")return response.detail;if(response?.detail&&typeof response.detail==="object"&&response.detail.message)return response.detail.message;return `Could not start checkout. Server returned ${status}.`}

export default function BillingPage(){
 const [loading,setLoading]=useState<PlanId|null>(null),[error,setError]=useState(""),[accepted,setAccepted]=useState(false);
 async function checkout(plan:PlanId){if(loading||!accepted)return;setLoading(plan);setError("");try{const request=await fetch("/api/backend/api/billing/initialize",{method:"POST",credentials:"include",cache:"no-store",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({plan:backendCode(plan),callback_url:`${window.location.origin}/payment/callback`})});const text=await request.text();let response:PaymentResponse|null=null;try{response=text?JSON.parse(text) as PaymentResponse:null}catch{response=null}if(!request.ok)throw new Error(errorMessage(response,request.status));if(!response?.authorization_url?.startsWith("https://"))throw new Error("Paystack did not return a valid checkout URL.");window.location.assign(response.authorization_url)}catch(reason){setError(reason instanceof Error?reason.message:"Could not start checkout.");setLoading(null)}}
 return <>
  <header className="page-header builder-header"><div><span className="eyebrow">Secure once-off access</span><h1>Choose your Makwande Careers plan</h1><p className="muted">Select the access period that fits your job search. No automatic renewal is added by these plans.</p></div><div className="builder-status"><span>Currency</span><strong>ZAR</strong></div></header>
  {error&&<div className="error" style={{marginBottom:18}}>{error}</div>}
  <section className="billing-includes"><div><span className="eyebrow">All plans include</span><h2>Everything required to build a stronger application</h2></div><div className="billing-shared">{shared.map(({title,text,icon:Icon})=><article key={title}><Icon size={22}/><div><strong>{title}</strong><p>{text}</p></div></article>)}</div></section>
  <div className="billing-grid">{(Object.entries(DISPLAY_PLANS) as Array<[PlanId,(typeof DISPLAY_PLANS)[PlanId]]>).map(([id,plan])=>{const premium=id==="premium_30_days",isLoading=loading===id;return <article className={`card pricing-card ${premium?"pricing-featured":""}`} key={id}>{premium&&<div className="pricing-badge">Best value</div>}<div><span className="eyebrow">{plan.duration_days}-day access</span><h2>{plan.name}</h2><div className="price-line"><strong>{formatZar(plan.amount)}</strong><span>once-off</span></div><p className="muted">Access ends after {plan.duration_days} days. Purchase again only when you choose.</p></div><div className="pricing-benefits">{benefits[id].map((benefit)=><div key={benefit}><CheckCircle2 size={18}/><span>{benefit}</span></div>)}</div><button type="button" className="button button-primary button-wide" disabled={loading!==null||!accepted} onClick={()=>void checkout(id)}>{isLoading?<><LoaderCircle className="spin-icon" size={18}/>Opening Paystack…</>:<><CreditCard size={18}/>Pay {formatZar(plan.amount)} securely</>}</button></article>})}</div>
  <section className="card checkout-consent"><label><input type="checkbox" checked={accepted} onChange={(event)=>setAccepted(event.target.checked)}/><span>I agree to the <Link href="/terms">Terms & conditions</Link> and acknowledge the <Link href="/privacy">Privacy notice</Link>, once-off price and selected access period.</span></label>{!accepted&&<small>Select this agreement to enable secure checkout.</small>}</section>
  <section className="card payment-trust"><ShieldCheck size={30}/><div><strong>Paystack secure checkout</strong><p className="muted">Card details are entered on Paystack&apos;s protected payment page. Makwande Careers does not store your card number, PIN, CVV or one-time password.</p><p className="payment-links"><Link href="/contact">Payment support</Link><Link href="/terms">Refund and access terms</Link></p></div></section>
 </>;
}
