import Image from "next/image";
import Link from "next/link";
import styles from "../legal.module.css";

export default function PrivacyPage(){return <div className={styles.page}><header className={styles.header}><Link className={styles.brand} href="/"><Image src="/makwande-careers-logo.jpeg" alt="" width={42} height={42}/>MAKWANDE CAREERS</Link><nav className={styles.nav}><Link href="/terms">Terms</Link><Link href="/contact">Contact</Link><Link href="/login">Sign in</Link></nav></header><main className={styles.main}><div className={styles.hero}><span className={styles.eyebrow}>POPIA privacy notice</span><h1>Your information stays yours.</h1><p>This notice describes how Makwande Careers processes personal information when you build a CV, use AI guidance or manage your account.</p></div><article className={styles.card}>
<section><h2>Information we process</h2><p>Account and contact details, career history, uploaded documents, CV content, preferences, payment references, security logs and the instructions you submit to career tools.</p></section>
<section><h2>Why we process it</h2><p>To provide requested career services, authenticate and secure accounts, generate documents and recommendations, process access through Paystack, respond to support requests and comply with legal obligations.</p></section>
<section><h2>AI processing</h2><p>Relevant candidate information may be sent to configured AI services to produce the feature you request. Do not upload unnecessary identity numbers, banking information, medical records or other special personal information.</p></section>
<section><h2>Sharing and security</h2><p>Information is shared only with service providers needed to operate the platform, such as hosting, database, AI and payment providers, subject to appropriate safeguards. Card entry takes place on Paystack&apos;s secure checkout.</p></section>
<section><h2>Your POPIA rights</h2><p>You may request access, correction or deletion of eligible information, object to certain processing, or raise a privacy concern. Some records may be retained where required for security, legal or financial compliance.</p></section>
<section><h2>Contact</h2><p>Email privacy and account requests to <a href="mailto:admin@makwandecareer.co.za">admin@makwandecareer.co.za</a>. We may ask you to verify your identity before acting on a request.</p></section>
</article></main><footer className={styles.footer}><span>© 2026 Makwande Careers</span><span><Link href="/terms">Terms & conditions</Link> · <Link href="/contact">Contact</Link></span></footer></div>}
