"use client";
import {templates,type CVSectionKey,type CVSettings,type CVTemplateKey} from "@/lib/cv-builder";
const labels:Record<CVSectionKey,string>={summary:"Professional Summary",experience:"Professional Experience",education:"Education",skills:"Core Skills",projects:"Projects",certifications:"Certifications",languages:"Languages",references:"References"};
export function CVBuilderSettings({template,setTemplate,settings,setSettings,sectionOrder,setSectionOrder}:{template:CVTemplateKey;setTemplate:(v:CVTemplateKey)=>void;settings:CVSettings;setSettings:(v:CVSettings)=>void;sectionOrder:CVSectionKey[];setSectionOrder:(v:CVSectionKey[])=>void;}){
 const move=(i:number,d:-1|1)=>{const n=[...sectionOrder],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];setSectionOrder(n)};
 return <div className="builder-settings-stack">
  <section className="card"><h3>Template gallery</h3><div className="template-gallery">{templates.map(([key,name])=><button type="button" key={key} className={`template-card ${template===key?"selected":""}`} onClick={()=>setTemplate(key)}><div className={`template-thumbnail template-thumbnail-${key}`}><span/><span/><span/><span/></div><strong>{name}</strong></button>)}</div></section>
  <section className="card form"><h3>Document settings</h3><div className="two-column"><div className="field"><label>Paper size</label><select className="input" value={settings.paperSize} onChange={e=>setSettings({...settings,paperSize:e.target.value as CVSettings["paperSize"]})}><option value="a4">A4</option><option value="letter">US Letter</option></select></div><div className="field"><label>Margins</label><select className="input" value={settings.margin} onChange={e=>setSettings({...settings,margin:e.target.value as CVSettings["margin"]})}><option value="narrow">Narrow</option><option value="standard">Standard</option><option value="wide">Wide</option></select></div></div>
  <div className="two-column"><div className="field"><label>Font</label><select className="input" value={settings.font} onChange={e=>setSettings({...settings,font:e.target.value as CVSettings["font"]})}>{["Arial","Helvetica","Calibri","Cambria","Garamond"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Accent colour</label><input className="input color-input" type="color" value={settings.accent} onChange={e=>setSettings({...settings,accent:e.target.value})}/></div></div>
  <div className="two-column"><div className="field"><label>Font size: {settings.fontSize}px</label><input className="input" type="range" min="10" max="15" value={settings.fontSize} onChange={e=>setSettings({...settings,fontSize:Number(e.target.value)})}/></div><div className="field"><label>Line spacing: {settings.lineHeight.toFixed(1)}</label><input className="input" type="range" min="1.2" max="1.8" step="0.1" value={settings.lineHeight} onChange={e=>setSettings({...settings,lineHeight:Number(e.target.value)})}/></div></div>
  <div className="settings-toggles">{[["showProjects","Projects"],["showCertifications","Certifications"],["showLanguages","Languages"],["showReferences","References"]].map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(settings[key as keyof CVSettings])} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/>{label}</label>)}</div></section>
  <section className="card"><h3>Section order</h3><div className="section-order-list">{sectionOrder.map((s,i)=><div className="section-order-item" key={s}><span>{i+1}</span><strong>{labels[s]}</strong><div><button type="button" onClick={()=>move(i,-1)}>↑</button><button type="button" onClick={()=>move(i,1)}>↓</button></div></div>)}</div></section>
 </div>
}
