"use client";
import { FormEvent, useEffect, useState } from "react";
import { Building2, Save } from "lucide-react";
import { api } from "@/lib/client-api";
import styles from "./company.module.css";

type Company={name:string;registration_number?:string;industry?:string;company_size?:string;website?:string;phone?:string;email?:string;location?:string;description?:string};
export default function CompanyPage(){
 const [company,setCompany]=useState<Company>({name:""});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{api<{company:Company|null}>("/api/employer/company").then(d=>d.company&&setCompany(d.company)).catch(()=>undefined)},[]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const d=await api<{company:Company}>("/api/employer/company",{method:"PUT",body:JSON.stringify(company)});setCompany(d.company);setMessage("Company profile saved.")}catch(x){setMessage(x instanceof Error?x.message:"Unable to save.")}finally{setSaving(false)}}
 return <main className={styles.page}><header><span><Building2 size={16}/> Company registration</span><h1>Build a trusted employer profile</h1><p>Complete your organisation details before publishing vacancies.</p></header><form onSubmit={submit}><section><h2>Organisation details</h2><div className={styles.grid}><label>Company name<input required value={company.name} onChange={e=>setCompany({...company,name:e.target.value})}/></label><label>Registration number<input value={company.registration_number||""} onChange={e=>setCompany({...company,registration_number:e.target.value})}/></label><label>Industry<input value={company.industry||""} onChange={e=>setCompany({...company,industry:e.target.value})}/></label><label>Company size<select value={company.company_size||""} onChange={e=>setCompany({...company,company_size:e.target.value})}><option value="">Select size</option><option>1-10</option><option>11-50</option><option>51-200</option><option>201-500</option><option>501+</option></select></label><label>Website<input type="url" value={company.website||""} onChange={e=>setCompany({...company,website:e.target.value})}/></label><label>Location<input value={company.location||""} onChange={e=>setCompany({...company,location:e.target.value})}/></label><label>Business email<input type="email" value={company.email||""} onChange={e=>setCompany({...company,email:e.target.value})}/></label><label>Phone<input value={company.phone||""} onChange={e=>setCompany({...company,phone:e.target.value})}/></label></div><label>Description<textarea rows={7} value={company.description||""} onChange={e=>setCompany({...company,description:e.target.value})}/></label></section>{message?<div className={styles.message}>{message}</div>:null}<button disabled={saving}><Save size={18}/>{saving?"Saving...":"Save company profile"}</button></form></main>
}
