import Image from "next/image";
import Link from "next/link";
import styles from "../legal.module.css";

export default function TermsPage(){return <div className={styles.page}><header className={styles.header}><Link className={styles.brand} href="/"><Image src="/makwande-careers-logo.jpeg" alt="" width={42} height={42}/>MAKWANDE CAREERS</Link><nav className={styles.nav}><Link href="/privacy">Privacy</Link><Link href="/contact">Contact</Link><Link href="/login">Sign in</Link></nav></header><main className={styles.main}><div className={styles.hero}><span className={styles.eyebrow}>Legal</span><h1>Terms & conditions</h1><p>These terms explain how candidates may use Makwande Careers, its AI career tools and paid access periods. Effective 22 July 2026.</p></div><article className={styles.card}>
<section><h2>1. Platform purpose</h2><p>Makwande Careers provides career-development tools including CV creation and revamp, ATS analysis, career guidance, application preparation, interview support and job-matching assistance. The platform does not guarantee interviews, employment, salary outcomes or employer decisions.</p></section>
<section><h2>2. Candidate responsibility and AI</h2><p>You must provide accurate information and review all AI-assisted content before using it. AI suggestions are guidance—not verified facts—and must never be used to invent qualifications, employers, duties or achievements.</p></section>
<section><h2>3. Access plans and payment</h2><p>The R45 plan provides 14 days of access and the R300 Premium plan provides 30 days of access. Both are once-off access purchases unless a checkout page expressly states otherwise. Payments are securely processed by Paystack; Makwande Careers does not collect or store full card details.</p></section>
<section><h2>4. Refund and payment queries</h2><p>If a payment is duplicated, access is not activated, or a technical fault prevents use, contact Makwande Careers promptly with the Paystack reference. Requests are assessed according to applicable consumer law and the circumstances of the transaction.</p></section>
<section><h2>5. Acceptable use</h2><p>You may not misuse the platform, access another person&apos;s account, upload unlawful material, bypass access controls, scrape the service, or use generated content to misrepresent your history.</p></section>
<section><h2>6. Documents and ownership</h2><p>You retain ownership of the career information and original documents you upload. You give Makwande Careers permission to process that information only to operate, secure and improve the services you request.</p></section>
<section><h2>7. Contact</h2><p>Questions about these terms can be sent to <a href="mailto:admin@makwandecareer.co.za">admin@makwandecareer.co.za</a> or through the <Link href="/contact">contact page</Link>.</p></section>
</article></main><footer className={styles.footer}><span>© 2026 Makwande Careers</span><span><Link href="/privacy">Privacy notice</Link> · <Link href="/contact">Contact</Link></span></footer></div>}
