"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/client-api";
import styles from "../account.module.css";

type Session={id:string;user_agent:string|null;ip_address:string|null;created_at:string;last_seen_at:string;expires_at:string;is_current:boolean};
type Event={id:string;event_type:string;ip_address:string|null;user_agent:string|null;created_at:string};

export default function SecurityPage(){
 const [sessions,setSessions]=useState<Session[]>([]),[events,setEvents]=useState<Event[]>([]),[currentPassword,setCurrent]=useState(""),[newPassword,setNew]=useState(""),[confirm,setConfirm]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){try{const [s,e]=await Promise.all([api<Session[]>("/api/account/security/sessions"),api<Event[]>("/api/account/security/activity")]);setSessions(s);setEvents(e)}catch(e){setError(e instanceof Error?e.message:"Unable to load security centre")}}
 useEffect(()=>{load()},[]);
 async function changePassword(event:FormEvent){event.preventDefault();setError("");setMessage("");if(newPassword!==confirm){setError("New passwords do not match");return}try{const result=await api<{message:string}>("/api/account/security/change-password",{method:"POST",body:JSON.stringify({current_password:currentPassword,new_password:newPassword})});setMessage(result.message);setCurrent("");setNew("");setConfirm("");load()}catch(e){setError(e instanceof Error?e.message:"Password update failed")}}
 async function revoke(id:string){await api(`/api/account/security/sessions/${id}`,{method:"DELETE"});setSessions(v=>v.filter(x=>x.id!==id))}
 async function revokeOthers(){const r=await api<{revoked_sessions:number}>("/api/account/security/sign-out-others",{method:"POST"});setMessage(`${r.revoked_sessions} other session(s) signed out.`);load()}
 return <><header className={styles.hero}><div><span className={styles.eyebrow}>Account protection</span><h1>Security</h1><p className={styles.muted}>Manage your password, devices and recent account activity.</p></div></header>{message&&<div className={styles.notice}>{message}</div>}{error&&<div className={styles.error}>{error}</div>}<div className={styles.grid}><form className={styles.card} onSubmit={changePassword}><div className={styles.cardHeader}><h2>Change password</h2></div><div className={styles.field}><label>Current password</label><input className={styles.input} type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} required/></div><div className={styles.field}><label>New password</label><input className={styles.input} type="password" minLength={12} value={newPassword} onChange={e=>setNew(e.target.value)} required/><small className={styles.muted}>Use at least 12 characters and a unique passphrase.</small></div><div className={styles.field}><label>Confirm new password</label><input className={styles.input} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></div><button className={styles.button}>Update password</button></form><section className={styles.card}><div className={styles.cardHeader}><h2>Active sessions</h2><button className={`${styles.button} ${styles.secondary}`} onClick={revokeOthers}>Sign out others</button></div><div className={styles.list}>{sessions.map(session=><div className={styles.item} key={session.id}><div><strong>{session.is_current?"This device":"Signed-in device"}</strong> {session.is_current&&<span className={styles.badge}>Current</span>}<p>{session.user_agent||"Unknown browser"}</p><small>{session.ip_address||"Unknown IP"} · Active {new Date(session.last_seen_at).toLocaleString()}</small></div>{!session.is_current&&<button className={`${styles.button} ${styles.danger}`} onClick={()=>revoke(session.id)}>Revoke</button>}</div>)}</div></section><section className={`${styles.card} ${styles.cardWide}`}><div className={styles.cardHeader}><h2>Recent security activity</h2></div><div className={styles.list}>{events.length===0?<div className={styles.empty}>No recent security events.</div>:events.map(event=><div className={styles.item} key={event.id}><div><strong>{event.event_type.replaceAll("_"," ")}</strong><p>{event.user_agent||"Unknown browser"}</p></div><small>{event.ip_address||"Unknown IP"}<br/>{new Date(event.created_at).toLocaleString()}</small></div>)}</div></section></div></>;
}
